# Properties file with JDBC and JPA settings.

# JDBC ?? ???? ?? (???)
jdbc.initLocation=classpath:db/${db.script}/schema.sql
jdbc.dataLocation=classpath:db/${db.script}/data.sql

# JPA ??
jpa.showSql=true
jpa.database=${jpa.database}
